version: '3.5'

services:
  ### UniversalTraderX (UTX) 
  utx:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    tty: true
    env_file:
      - ../.env
    ports:
      - "8080:8080"
      # Add other necessary ports for UTX
    volumes:
      - ../:/app
    container_name: utx
    # command: bash -c "python /app/main.py runserver 0.0.0.0:8080"
    environment:
      - DJANGO_DB_HOST=postgres
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=utx_database
      - DJANGO_DB_USER=utx_user
      - DJANGO_DB_PASSWORD=utx_password

  ### PostgreSQL Database 
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=utx_database
      - POSTGRES_USER=utx_user
      - POSTGRES_PASSWORD=utx_password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
